# Generated by Django 4.1.3 on 2023-01-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0002_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('date', models.DateTimeField()),
                ('user_name', models.CharField(default='admin', max_length=100)),
            ],
        ),
    ]
